### ISSUE TITLE
make a model class 

### ISSUE THREAD

**Issue by varde80** [varde80/aimat#2]
make a famous cnn model as a class in aimat/model/****.py

resnet, resnext,  convnext, vit.....

the important parameters will be given in the yaml file under conf/model/ ****.py

the model shoud be generalize to change w,h, c and so on 

* plz make your own branch

**Comment by namng-uwu** [comment]
@varde80 Professor, please check the new commit #4 


The following models have been added in aimat/models:

    resnet.py
    resnext.py
    vit.py
    vgg.py

The following configs have been added in conf/model:

    resnet.yaml
    resnext.yaml
    vit.yaml
    vgg.yaml

Modified aimat/model/init.py to accept new models

Added config2.yaml in conf/config2.yaml to test new models. 

In main.py, changed config -> config2
